# Generated by Django 5.0.2 on 2026-08-26 15:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('DEGRADED', 'Degraded')], default='CONNECTED', max_length=20)),
                ('django_endpoint', models.URLField(default='http://127.0.0.1:8000/api')),
                ('active_recordings_count', models.PositiveIntegerField(default=0)),
                ('total_cameras', models.PositiveIntegerField(default=0)),
                ('online_cameras', models.PositiveIntegerField(default=0)),
                ('offline_cameras', models.PositiveIntegerField(default=0)),
                ('cpu_usage_percent', models.FloatField(default=0.0)),
                ('ram_usage_percent', models.FloatField(default=0.0)),
                ('ffmpeg_running_instances', models.PositiveIntegerField(default=0)),
                ('system_uptime_seconds', models.PositiveBigIntegerField(default=0)),
                ('last_sync_time', models.CharField(default='Just now', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Tapo Surveillance VMS', max_length=100)),
                ('default_camera_id', models.UUIDField(blank=True, null=True)),
                ('default_recording_duration_minutes', models.PositiveIntegerField(default=15)),
                ('segment_duration_minutes', models.PositiveIntegerField(default=30)),
                ('storage_location', models.CharField(max_length=500)),
                ('retention_period_days', models.PositiveIntegerField(default=14)),
                ('is_auto_recording_enabled', models.BooleanField(default=True)),
                ('is_motion_recording_enabled', models.BooleanField(default=True)),
                ('motion_sensitivity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('sound_alerts', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('auto_cycle_interval_seconds', models.PositiveIntegerField(default=10)),
                ('django_api_url', models.URLField(default='http://127.0.0.1:8000/api')),
                ('ffmpeg_hardware_acc', models.CharField(choices=[('auto', 'Auto'), ('nvenc', 'NVIDIA NVENC'), ('qsv', 'Intel Quick Sync'), ('cpu', 'CPU Only')], default='auto', max_length=10)),
                ('snapshot_format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG')], default='jpeg', max_length=10)),
                ('high_storage_alert_threshold', models.PositiveIntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='SurveillanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera_id', models.UUIDField(blank=True, null=True)),
                ('camera_name', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('MOTION_DETECTED', 'Motion Detected'), ('RECORDING_STARTED', 'Recording Started'), ('RECORDING_STOPPED', 'Recording Stopped'), ('CAMERA_OFFLINE', 'Camera Offline'), ('CAMERA_ONLINE', 'Camera Online'), ('STORAGE_WARNING', 'Storage Warning')], max_length=30)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Surveillance Event',
                'verbose_name_plural': 'Surveillance Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_surv_timesta_0e81b2_idx'), models.Index(fields=['camera_id', '-timestamp'], name='system_surv_camera__b48868_idx'), models.Index(fields=['event_type', '-timestamp'], name='system_surv_event_t_5c9b6b_idx'), models.Index(fields=['severity', '-timestamp'], name='system_surv_severit_743c3a_idx')],
            },
        ),
    ]
