# Generated by Django 5.0.2 on 2026-08-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='storage_location',
            field=models.CharField(default='C:\\Users\\Comme\\Videos', max_length=500),
        ),
    ]
