# Generated by Django 5.0.2 on 2026-08-26 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Recording start timestamp')),
                ('end_time', models.DateTimeField(blank=True, help_text='Recording end timestamp', null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Recording duration in seconds')),
                ('file_size_mb', models.FloatField(default=0.0, help_text='File size in megabytes')),
                ('storage_file_path', models.CharField(help_text='Full path to video file', max_length=500)),
                ('video_url', models.URLField(blank=True, help_text='URL for video playback', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL for video thumbnail', max_length=500)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('RECORDING', 'Recording'), ('FAILED', 'Failed')], default='RECORDING', max_length=20)),
                ('trigger_type', models.CharField(choices=[('MANUAL', 'Manual'), ('MOTION', 'Motion Detection'), ('SCHEDULED', 'Scheduled'), ('CONTINUOUS', 'Continuous')], default='MANUAL', max_length=20)),
                ('resolution', models.CharField(help_text='Video resolution', max_length=50)),
                ('fps', models.PositiveIntegerField(help_text='Frames per second')),
                ('bitrate_kbps', models.PositiveIntegerField(help_text='Video bitrate in kbps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_number', models.PositiveIntegerField(help_text='Segment sequence number')),
                ('start_time', models.DateTimeField(help_text='Segment start timestamp')),
                ('end_time', models.DateTimeField(help_text='Segment end timestamp')),
                ('file_path', models.CharField(help_text='Path to segment file', max_length=500)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, help_text='Segment file size')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Segment duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='recordings.recording')),
            ],
            options={
                'verbose_name': 'Recording Segment',
                'verbose_name_plural': 'Recording Segments',
                'ordering': ['recording', 'segment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['camera', '-start_time'], name='recordings__camera__e72a78_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['status'], name='recordings__status_a2963b_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['trigger_type'], name='recordings__trigger_03f296_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['-start_time'], name='recordings__start_t_807aa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingsegment',
            unique_together={('recording', 'segment_number')},
        ),
    ]
