# Generated by Django 5.0.2 on 2026-08-26 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-friendly camera name', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Camera IP address')),
                ('port', models.PositiveIntegerField(default=554, help_text='RTSP port')),
                ('onvif_port', models.PositiveIntegerField(blank=True, default=2020, help_text='ONVIF port for PTZ control', null=True)),
                ('username', models.CharField(help_text='Camera authentication username', max_length=50)),
                ('password', models.CharField(help_text='Camera authentication password', max_length=100)),
                ('rtsp_stream_path', models.CharField(default='/stream1', help_text='Main stream path (e.g., /stream1)', max_length=200)),
                ('sub_stream_path', models.CharField(default='/stream2', help_text='Sub stream path (e.g., /stream2)', max_length=200)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('CONNECTING', 'Connecting'), ('ERROR', 'Error')], default='OFFLINE', max_length=20)),
                ('is_recording', models.BooleanField(default=False, help_text='Currently recording')),
                ('is_enabled', models.BooleanField(default=True, help_text='Camera is enabled for monitoring')),
                ('recording_enabled', models.BooleanField(default=True, help_text='Recording is enabled for this camera')),
                ('resolution', models.CharField(default='1920x1080', help_text='Current video resolution', max_length=50)),
                ('fps', models.PositiveIntegerField(default=25, help_text='Frames per second')),
                ('bitrate_kbps', models.PositiveIntegerField(default=2048, help_text='Video bitrate in kbps')),
                ('model', models.CharField(default='Tapo TC40 Outdoor Pan/Tilt', help_text='Camera model', max_length=100)),
                ('location', models.CharField(help_text='Physical location description', max_length=200)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address', max_length=17, null=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Camera firmware version', max_length=100, null=True)),
                ('pan_tilt_supported', models.BooleanField(default=True, help_text='Camera supports pan/tilt control')),
                ('ptz_current_pan', models.FloatField(default=0.0, help_text='Current pan position')),
                ('ptz_current_tilt', models.FloatField(default=0.0, help_text='Current tilt position')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last successful communication')),
                ('error_reason', models.TextField(blank=True, help_text='Last error message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Snapshot filename', max_length=255)),
                ('file_path', models.CharField(help_text='Full file path', max_length=500)),
                ('file_size_bytes', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('width', models.PositiveIntegerField(help_text='Image width in pixels')),
                ('height', models.PositiveIntegerField(help_text='Image height in pixels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Camera Snapshot',
                'verbose_name_plural': 'Camera Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
